name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        flavor: [win32, win64]
        sharing: [shared, static]
        freedom: [nonfree, freeonly]
        stability: [stable, unstable]
    steps:
      - name: variable preparation
        id: prep
        run: |
          if ['${{ matrix.sharing }}' == 'shared']
          then
              echo "::set-output name=sharingflag::--build-ffmpeg-static=n --build-ffmpeg-shared=y"
          else
              echo "::set-output name=sharingflag::--build-ffmpeg-static=y --build-ffmpeg-shared=n"
          fi
          if ['${{ matrix.freedom }}' == 'nonfree']
          then
              echo "::set-output name=freeflag::--disable-nonfree=n"
          else
              echo "::set-output name=freeflag::--disable-nonfree=y"
          fi
          if ['${{ matrix.stability }}' == 'stable']
          then
              echo "::set-output name=stableflag::--prefer-stable=y"
          else
              echo "::set-output name=stableflag::--prefer-stable=n"
          fi
      - uses: actions/checkout@v2
      - name: apt dependencies
        run: |
          sudo apt install subversion \
          ragel \
          curl \
          texinfo \
          g++ \
          bison \
          flex \
          cvs \
          yasm \
          automake \
          libtool \
          autoconf \
          gcc \
          cmake \
          git \
          make \
          pkg-config \
          zlib1g-dev \
          unzip \
          pax \
          nasm \
          gperf \
          autogen \
          bzip2 \
          autoconf-archive \
          p7zip-full \
          meson \
          clang \
          python3-distutils \
          python-is-python3 -y
      - run: ./cross_compile_ffmpeg.sh ${{ steps.prep.outputs.sharingflag }} ${{ steps.prep.outputs.stableflag }} ${{ steps.prep.outputs.freeflag }} --sandbox-ok=y --compiler-flavors=${{ matrix.flavor }} --build-x264-with-libav=y --gcc-cpu-count=$(nproc)
      - uses: actions/upload-artifact@v2
        with:
          name: win-${{ matrix.flavor }}-${{ matrix.sharing }}-${{ matrix.freedom }}-${{ matrix.stability }}
          path: sandbox/${{ matrix.flavor }}/ffmpeg_git
