name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: apt dependencies
        run: |
          sudo apt install subversion \
          ragel \
          curl \
          texinfo \
          g++ \
          bison \
          flex \
          cvs \
          yasm \
          automake \
          libtool \
          autoconf \
          gcc \
          cmake \
          git \
          make \
          pkg-config \
          zlib1g-dev \
          unzip \
          pax \
          nasm \
          gperf \
          autogen \
          bzip2 \
          autoconf-archive \
          p7zip-full \
          meson \
          clang \
          python3-distutils \
          python-is-python3 -y
      - run: ./cross_compile_ffmpeg.sh --build-ffmpeg-static=y --prefer-stable=n --disable-nonfree=n --sandbox-ok=y --compiler-flavors=win64 --build-x264-with-libav=y --gcc-cpu-count=2
      - uses: actions/upload-artifact@v2
        with:
          name: sandbox
          path: sandbox
